### ISSUE TITLE
iOSのSafariが電話番号と認識した整数のレイアウトが崩れる

### ISSUE THREAD

**Issue by keijak** [Tiramister/IntegerInformation#1]
iPadのSafariから見たときに、調べたい整数に対して電話をかけるリンクをブラウザが勝手に生成するせいでレイアウトが崩れることがあります。

スクリーンショットです。(iPadOS 15.0.2)
![DAB893DE-F848-451B-AB8A-758EE1A7B9BB](https://user-images.githubusercontent.com/10389686/150406418-98b5a853-26a2-412a-962b-a839a46f6d29.jpeg)

HTMLにメタタグを入れておくと無効化できるようです。
https://qiita.com/7note/items/0b10db27095d5233c2ae

**Comment by Tiramister** [comment]
issue ありがとうございます。大変対応が遅れて申し訳ありません。
提供していただいた記事を参考に修正を加えました。こちらには iOS の環境がなくデバッグができなかったので、もしまだ不具合が生じているようでしたら教えていただけると幸いです。

**Comment by keijak** [comment]
手元の環境で修正を確認できました。ご対応ありがとうございます！
